add limit_results to DataViewSet
fullctl/fullctl pull request #210
Opened 2024-01-24 23:08 UTC by jason20c

2024-01-25 13:33 UTC, vegu requested changes

2024-01-25 13:33 UTC, vegu commented on src/fullctl/django/rest/views/service_bridge.py
> +        if self.limit_results > 0:
@jason20c i think, since we also have the request object available, lets add a secondary on switch for this through a `limit` parameter passed with the request.

So keep this, but also add that :) 

Reasoning: for stuff like autocomplete we can probably limit to 25 or something, and i am not sure we want to impose a 200 limit on the pdbctl net view as a default, since i don't know off the top off my head what that is going to affect in peerctl and so on.

2024-01-25 18:43 UTC, jason20c commented on src/fullctl/django/rest/views/service_bridge.py
> +        if self.limit_results > 0:
I changed it to pass in the number through the request itself.

2024-01-30 11:33 UTC, vegu approved these changes

2024-02-12 13:33 UTC, merged