Add stuck queue check to health status
fullctl/fullctl pull request #223
Opened 2024-02-20 20:50 UTC by Genza999

This PR adds a task stuck queue check for checking pending tasks that:
- Have lasted a maximum threshold as pending
- Have exceeded the maximum number of pending tasks allowed

The implementation shoould cause the health check page to error if there are N amount of unprocessed tasks or if there are unprocessed tasks older than X time.
The task is : https://app.clickup.com/t/14289126/FC-2768

2024-02-21 11:24 UTC, vegu requested changes

2024-02-21 11:24 UTC, vegu commented on src/fullctl/django/settings/__init__.py
> +        self.set_option("TASK_MAX_AGE_THRESHOLD", 24)
@Genza999 lets add a comment noting unit size (hours)

2024-02-21 11:24 UTC, vegu commented on src/fullctl/django/settings/__init__.py
>          self.set_option("TASK_RECHECK_DECAY_MAX", 3600)
@Genza999 while you're in here please also add a comment here stating this is seconds and controls the maximum re-evaluation decay for task qualification

2024-02-21 11:24 UTC, vegu commented on src/fullctl/django/views/__init__.py
> +    pending_tasks = Task.objects.filter(status="pending")
@Genza999 lets add `queue_id__isnull=True` to the filter here, so we only check tasks that haven't been picked up by a task worker yet. (e.g., the queue is getting backed up)

2024-02-21 15:35 UTC, Genza999 commented on src/fullctl/django/views/__init__.py
> +    pending_tasks = Task.objects.filter(status="pending")
Added, thanks!

2024-02-21 15:35 UTC, Genza999 commented on src/fullctl/django/settings/__init__.py
> +        self.set_option("TASK_MAX_AGE_THRESHOLD", 24)
Added, thanks!

2024-02-22 12:44 UTC, vegu approved these changes

2024-02-22 12:45 UTC, vegu commented
PR looks good, but i think we need to make sure all task queues are cleaned before we deploy this, so retargeting to `draft-pr-branch` for now.

2024-02-22 15:54 UTC, vegu commented
Lets rebase and adjust this for the changes in https://github.com/fullctl/fullctl/pull/226 once that's merged

2024-03-21 14:04 UTC, vegu commented
something about the commit history is janky, will reopen a new pr

2024-03-21 14:25 UTC, merged