fix: remove peeringdb library and peeringdb_sync command
fullctl/fullctl pull request #239
Opened 2024-03-28 13:11 UTC by Genza999

Implementataion here does the following:
- Remove fullctl_peeringdb_sync command from fullctl
- Remove peeringdb  library and django-peeringdb from fullctl

Task:
https://app.clickup.com/t/14289126/FC-3048

2024-04-01 09:09 UTC, vegu requested changes

2024-04-01 09:09 UTC, vegu commented on pyproject.toml
> +django-countries = "^7.6"
@Genza999 lets do >= here

2024-04-01 09:09 UTC, vegu commented on CHANGELOG.md
> -
@Genza999 what's causing these white-space changes?

2024-04-01 09:09 UTC, vegu commented on Ctl/VERSION
> +1.13.0-rc.4
@Genza999 more unintentional white-space changes - this is an automatically updated / maintained file, so we don't want to make any changes to it

2024-04-02 14:40 UTC, vegu commented
Note that this shouldn't be merged until the required changes are merged in pdbctl (e.g., the implementation of the sync command moved to there)

2024-04-02 14:57 UTC, vegu commented
@Genza999 i think this also had merge conflicts (plus the commit history seems off) - might be good to rebase?

2024-04-03 01:02 UTC, Genza999 commented on pyproject.toml
> +django-countries = "^7.6"
This has been implemented

2024-04-03 01:02 UTC, Genza999 commented on CHANGELOG.md
> -
White space changes have been reverted!

2024-04-03 01:02 UTC, Genza999 commented on Ctl/VERSION
> +1.13.0-rc.4
White space/unecessary changes have been reverted

2024-04-03 01:03 UTC, Genza999 commented
> @Genza999 i think this also had merge conflicts (plus the commit history seems off) - might be good to rebase?

Conflicts with base branch have been resolved

2024-04-08 11:12 UTC, vegu approved these changes

2024-04-08 11:14 UTC, vegu requested changes
There seems to be a failing test requiring django-peeringdb still @Genza999

2024-04-24 09:45 UTC, merged