Feat: white label components
fullctl/fullctl pull request #241
Opened 2024-04-11 15:54 UTC by Genza999

- [Fullctl template updates to apply whitelabeling if it exists](https://app.clickup.com/t/14289126/FC-3114)
- [Fullctl / aaactl service bridge client objects for loading white label components from aaactl](https://app.clickup.com/t/14289126/FC-3111)

2024-04-11 23:20 UTC, vegu requested changes

2024-04-11 23:20 UTC, vegu commented on src/fullctl/django/context_processors.py
> +            "name": context["org_whitelabel"]["org"]["name"]
@Genza999 i don't think we should lose the service tag from the name - can concat maybe?

2024-04-11 23:20 UTC, vegu commented on src/fullctl/django/context_processors.py
> -            "slug": settings.SERVICE_TAG,
@Genza999 the slug isn't affected by the white labeling and must stay the service tag

2024-04-11 23:20 UTC, vegu commented on src/fullctl/django/context_processors.py
> +            "org_namespace": context["org_whitelabel"]["org"]["name"]
@Genza999 org_namespace is the permissioning namespace and needs to be unaffected by the white labeling.

2024-04-12 01:55 UTC, Genza999 commented on src/fullctl/django/context_processors.py
> -            "slug": settings.SERVICE_TAG,
This has been fixed!

2024-04-12 01:55 UTC, Genza999 commented on src/fullctl/django/context_processors.py
> +            "org_namespace": context["org_whitelabel"]["org"]["name"]
Fixed!!

2024-04-12 01:55 UTC, Genza999 commented on src/fullctl/django/context_processors.py
> +            "name": context["org_whitelabel"]["org"]["name"]
Fixed!!

2024-04-12 22:24 UTC, grizz commented on src/fullctl/django/context_processors.py
> +        service_logo_dark=context["org_whitelabel"]["logo_url"]
Nitpick: These are quite hard to read with that formatting, could we do it a different way?

2024-04-16 00:35 UTC, Genza999 commented on src/fullctl/django/context_processors.py
> +        service_logo_dark=context["org_whitelabel"]["logo_url"]
This has been fixed, thanks

2024-04-16 08:52 UTC, vegu requested changes

2024-04-16 08:52 UTC, vegu commented on src/fullctl/django/context_processors.py
> +        print(f"Error fetching org whitelabel: {e}")
should use structlog

2024-04-16 08:52 UTC, vegu commented on src/fullctl/django/context_processors.py
> +                "css": {
That can probably just pass through `css_dict` as is?

2024-04-16 08:52 UTC, vegu commented on src/fullctl/django/context_processors.py
> +        service_tag = context["org_whitelabel"].get("name")
i dont think this should override the service_tag - ixctl is ixctl, regardless of whitelabeling.

i believe this is overwritten because it sets the `alt` value of the logo, and it'd be better to just define a new separate variable for that, like `logo_alt_text` or something.

2024-04-16 08:52 UTC, vegu commented on src/fullctl/django/context_processors.py
> +            org_whitelabel = OrganizationWhiteLabeling().first(
Eventually we will want to have the default whitelabel logic happen in aaactl.

The current approach seems fine for now, but ideally it'd do one request to aaactl and come back either with the org specific white label or the default white label.

Lets at the very least add a comment note here that we may want to look at that some more.

2024-04-16 08:52 UTC, vegu commented on src/fullctl/django/templates/common/v2/app/base.html
> +if (primaryColorValue) {
if this is mapping `css-property-name` to `whitelabel-property-value` this ideally would be controlled through a mapping.

its more manageable and easier to read and edit then a set of `if` conditionals.

2024-04-16 08:52 UTC, vegu commented on src/fullctl/django/context_processors.py
> +            slug=org_slug
to be in line with how we usually do org slug filtering in other service bridge views this should be `org=org_slug`

2024-04-17 13:00 UTC, Genza999 commented on src/fullctl/django/context_processors.py
> +        print(f"Error fetching org whitelabel: {e}")
Has been implemented, thanks

2024-04-17 13:01 UTC, Genza999 commented on src/fullctl/django/context_processors.py
> +        service_tag = context["org_whitelabel"].get("name")
logo_alt_text has been added, thanks

2024-04-17 13:01 UTC, Genza999 commented on src/fullctl/django/context_processors.py
> +            org_whitelabel = OrganizationWhiteLabeling().first(
Noted, TODO comment has been added here

2024-04-17 13:01 UTC, Genza999 commented on src/fullctl/django/context_processors.py
> +            slug=org_slug
This has been refactored, thanks

2024-04-17 13:02 UTC, Genza999 commented on src/fullctl/django/context_processors.py
> +                "css": {
This has been refactored, thanks!

2024-04-17 17:17 UTC, vegu requested changes

2024-04-17 17:17 UTC, vegu commented on src/fullctl/django/context_processors.py
> +                "html_title": org_whitelabel.html_title,
@Genza999 drop in favor of using the org name

2024-04-17 17:18 UTC, vegu commented on src/fullctl/django/templates/common/v2/app/base.html
> +if (primaryColorValue) {
@Genza999 making sure this isn't lost

2024-04-17 17:32 UTC, vegu requested changes

2024-04-17 17:32 UTC, vegu commented on src/fullctl/django/templates/common/v2/app/base.html
> +                <span class="text-item">{{ service_app.slug }}</span>
@Genza999 the content text should be the app name not the slug (Since that will have proper formatting, e.g., PeerCtl over peerctl)

2024-04-17 18:25 UTC, Genza999 commented on src/fullctl/django/context_processors.py
> +                "html_title": org_whitelabel.html_title,
This has been dropped, thanks

2024-04-17 18:59 UTC, Genza999 commented on src/fullctl/django/templates/common/v2/app/base.html
> +if (primaryColorValue) {
Hrm, am not sure how to implement this, could you elaborate please?

2024-04-17 21:48 UTC, vegu commented on src/fullctl/django/templates/common/v2/app/base.html
> +if (primaryColorValue) {
was thinking something along the line of

```
BRANDING_PROPERTY_MAP = {
  "primary_color": "--clr-accent-400"
}
```

and then you can just loop over that and apply those that exist in org_whitelabel.css

@Genza999

2024-04-18 02:53 UTC, grizz approved these changes

2024-04-18 03:17 UTC, vegu commented on src/fullctl/django/templates/common/v2/app/base.html
> +if (primaryColorValue) {
lets revisit this down the line

2024-04-18 03:29 UTC, vegu requested changes

2024-04-18 03:29 UTC, vegu commented on src/fullctl/django/context_processors.py
> +            org_whitelabel = OrganizationWhiteLabeling().first(org="fullctl")
@Genza999 I think we should make the default branding not come from the service bridge / db since that introduces a hard dependency on that specific org and white label entry to exist in aaactl.

Instead this can has exist as a hardcoded class/object in fullctl/fullctl

2024-04-18 10:27 UTC, Genza999 commented on src/fullctl/django/context_processors.py
> +            org_whitelabel = OrganizationWhiteLabeling().first(org="fullctl")
This has been refactored, kindly review

2024-04-18 10:35 UTC, vegu requested changes

2024-04-18 10:35 UTC, vegu commented on src/fullctl/django/util.py
> +    "html_footer": "Copyright © 2014 - 2024 FullCtl, LLC",
@Genza999 this should still generate a dynamic current year

2024-04-18 11:32 UTC, Genza999 commented on src/fullctl/django/util.py
> +    "html_footer": "Copyright © 2014 - 2024 FullCtl, LLC",
Yeah, this has been refactored

2024-04-18 11:55 UTC, vegu approved these changes

2024-04-18 14:40 UTC, vegu commented
replaced by #245

2024-04-18 14:40 UTC, closed without merging