Unresolvable task op should cause a hard failure
fullctl/fullctl pull request #254
Opened 2024-05-02 15:58 UTC by Genza999

This is an implementation for the CU bug:
https://app.clickup.com/t/14289126/FC-3420

2024-05-02 19:45 UTC, Genza999 commented
Task linked: https://app.clickup.com/t/14289126/FC-3420

2024-05-06 10:56 UTC, vegu requested changes

2024-05-06 10:56 UTC, vegu commented on src/fullctl/django/tasks/__init__.py
> +        raise
@Genza999 i made a typo in the task description - this should NOT actually raise an error, we just want it to log an error and continue on.

2024-05-06 20:56 UTC, Genza999 commented on src/fullctl/django/tasks/__init__.py
> +        raise
This has been refactored, thanks!

2024-05-07 10:20 UTC, vegu approved these changes

2024-05-08 11:46 UTC, vegu requested changes
@Genza999 actually - i think this needs another test 

i want us to check that this works smoothly when a task scheduler sets a task op that doesn't exist (which is what caused the creation of the ticket)

so a test that
- sets up a task schedule referencing a non existing task
- runs the fullctl poll task logic
- smoothly identifies that the task doesn't exist, logs an error, and returns to the loop

2024-05-10 02:21 UTC, Genza999 commented
> @Genza999 actually - i think this needs another test
> 
> i want us to check that this works smoothly when a task scheduler sets a task op that doesn't exist (which is what caused the creation of the ticket)
> 
> so a test that
> 
> * sets up a task schedule referencing a non existing task
> * runs the fullctl poll task logic
> * smoothly identifies that the task doesn't exist, logs an error, and returns to the loop

Good call, turns out this error was being raised from a different point, 
in **create_tasks_from_json** function at 
`task = model.create_task(timeout=timeout, user=user, org=org, *args, **kwargs)`
since if there is no op, there is no model and was causing an Attribute error before continuing processing.

2024-05-13 11:37 UTC, vegu commented
@Genza999 needs linting please

2024-05-14 15:53 UTC, merged